# Site settings
title: BeautifulNote
email: admin@beautifulnote.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: ananth
github_username:  ananthp

# Build settings
markdown: kramdown

# Custom

excerpt_seperator: <!--more-->

# download links

theory2: link/to/theory2.pdf
