# Site settings
title: BeautifulNote
email: admin@beautifulnote.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beautifulnote.com" # the base hostname & protocol for your site
twitter_username: ananth
github_username:  ananthp

# Build settings
markdown: kramdown

# Custom

excerpt_seperator: <!--more-->
