# Site settings
title: BeautifulNote
description: > # this means to ignore newlines until "baseurl:"
     Blog of Ananth Pattabiraman, musician and co-founder of Kuyil Carnatic Apps. Here I write about Carnatic music, advancements in technology for making and learning music. I also make and share music scores here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://beautifulnote.com"
logo: "/favicon.png"
twitter_username: ananth
github_username:  ananthp
twitter:
  username: ananth
facebook:
  publisher: https://www.facebook.com/ananth.composes

# Build settings
markdown: kramdown

# Custom
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

excerpt_seperator: <!--more-->

# site level variables
new_tab: 'target="_blank" rel="noopener noreferrer"'
author: Ananth Pattabiraman

shruti_app_link: "https://play.google.com/store/apps/details?id=org.kuyil.shruti"
sadhakam_app_link: "https://play.google.com/store/apps/details?id=org.kuyil.sadhakam"
shrutibox_app_link: "https://play.google.com/store/apps/details?id=org.kuyil.shrutibox"

shruti_app_description: Instantly see the swaram you're singing or playing. Tune any instrument accurately. Perfect your singing and playing.
sadhakam_app_description: Improve your swara gnanam with interactive exercises. Develop the skill to identify swarams from what you hear.
shrutibox_app_description: Concert grade shruti box app. Authentic tambura sound. Very accurate. Clear even on phone speakers. Sounds great with external speakers and headphones.
